version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: pw_kp_poc
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data:
