name: node_red
services:
  node-red:
    stdin_open: true
    tty: true
    ports:
      - 1880:1880
    volumes:
      - node_red_data:/data
    container_name: mynodered
    image: nodered/node-red
volumes:
  node_red_data:
    external: true
    name: node_red_data
