export const external_members = [
	{
		id: 1, // Age < 18
		firstName: 'Prinnada',
		lastName: 'Comewinit',
		nationality: 'Thai',
		email: 'prinnada.c@gmail.com',
		phoneNumber: '0812345678',
		age: 16,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 2, // Age = 18
		firstName: 'Pipat',
		lastName: 'Kaewsakulchai',
		nationality: 'Thai',
		email: 'pipat.k@gmail.com',
		phoneNumber: '0812345679',
		age: 18,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 3, // Age > 18
		firstName: 'NeungZ',
		lastName: 'Kawaii',
		nationality: 'Thai',
		email: 'neungz.k@gmail.com',
		phoneNumber: '0812345679',
		age: 30,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 4, // Not active, not delete
		firstName: 'Suriya',
		lastName: 'Metharom',
		nationality: 'Thai',
		email: 'suriya@gmail.com',
		phoneNumber: '0812345679',
		age: 18,
		is_active: false,
		is_delete: false,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 5, // Not active, deleted
		firstName: 'Arthit',
		lastName: 'Wattana',
		nationality: 'Thai',
		email: 'art.w@gmail.com',
		phoneNumber: '0812345679',
		age: 20,
		is_active: false,
		is_delete: true,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 6, // Active, not delete
		firstName: 'Somchai',
		lastName: 'Metharom',
		nationality: 'Thai',
		email: 'somchai.m@gmail.com',
		phoneNumber: '0812345679',
		age: 22,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 7, // Active, deleted
		firstName: 'Kulap',
		lastName: 'Bunnag',
		nationality: 'Thai',
		email: 'kulap.b@gmail.com',
		phoneNumber: '0812345679',
		age: 24,
		is_active: true,
		is_delete: true,
		origin: 'Palace Blade',
		external_id: 'a001',
	},
	{
		id: 8, // Age < 20
		firstName: 'Ming',
		lastName: 'Wei',
		nationality: 'Chinese',
		email: 'mingming.w@gmail.com',
		phoneNumber: '0812345679',
		age: 16,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 9, // Age = 20
		firstName: 'Yang',
		lastName: 'Yu',
		nationality: 'Chinese',
		email: 'yuyuyang.y@gmail.com',
		phoneNumber: '0812345679',
		age: 20,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 10, // Age > 20
		firstName: 'Xun',
		lastName: 'Xu',
		nationality: 'Chinese',
		email: 'xunxu@gmail.com',
		phoneNumber: '0812345679',
		age: 30,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 11, // Not active, not delete
		firstName: 'Hua',
		lastName: 'Xu',
		nationality: 'Chinese',
		email: 'huaxu@gmail.com',
		phoneNumber: '0812345679',
		age: 18,
		is_active: false,
		is_delete: false,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 12, // Not active, deleted
		firstName: 'Heng',
		lastName: 'Lu',
		nationality: 'Chinese',
		email: 'luheng@gmail.com',
		phoneNumber: '0812345679',
		age: 20,
		is_active: false,
		is_delete: true,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 13, // Active, not delete
		firstName: 'Tao',
		lastName: 'Xiao',
		nationality: 'Chinese',
		email: 'xiaotao@gmail.com',
		phoneNumber: '0812345679',
		age: 22,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 14, // Active, deleted
		firstName: 'Long',
		lastName: 'Chu',
		nationality: 'Chinese',
		email: 'longlong.c@gmail.com',
		phoneNumber: '0812345679',
		age: 24,
		is_active: true,
		is_delete: true,
		origin: 'Palace Blade International',
		external_id: 'a001',
	},
	{
		id: 15, // Age < 20
		firstName: 'Tiana',
		lastName: 'Robb',
		nationality: 'French',
		email: 'tiana.r@gmail.com',
		phoneNumber: '1234567890',
		age: 16,
		is_active: true,
		is_delete: false,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 16, // Age = 20
		firstName: 'Severina',
		lastName: 'Scavo',
		nationality: 'French',
		email: 'scavo.s@gmail.com',
		phoneNumber: '1234567890',
		age: 20,
		is_active: true,
		is_delete: false,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 17, // Age > 20
		firstName: 'Roseline',
		lastName: 'Guillot',
		nationality: 'French',
		email: 'roseline.g@gmail.com',
		phoneNumber: '1234567890',
		age: 30,
		is_active: true,
		is_delete: false,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 18, // Not active, not delete
		firstName: 'Sylvain',
		lastName: 'Garnier',
		nationality: 'French',
		email: 'garnier.s@gmail.com',
		phoneNumber: '1234567890',
		age: 18,
		is_active: false,
		is_delete: false,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 19, // Not active, deleted
		firstName: 'Betania',
		lastName: 'Acosta',
		nationality: 'French',
		email: 'betania.a@gmail.com',
		phoneNumber: '1234567890',
		age: 20,
		is_active: false,
		is_delete: true,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 20, // Active, not delete
		firstName: 'Cristopher',
		lastName: 'Aguado',
		nationality: 'French',
		email: 'cristopher.a@gmail.com',
		phoneNumber: '1234567890',
		age: 22,
		is_active: true,
		is_delete: false,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
	{
		id: 21, // Active, deleted
		firstName: 'Lilia',
		lastName: 'Rojasu',
		nationality: 'French',
		email: 'liliad.r@gmail.com',
		phoneNumber: '1234567890',
		age: 24,
		is_active: true,
		is_delete: true,
		origin: 'XCALIBER',
		external_id: 'a001',
	},
];
