export const partners = [
	{
		id: 1,
		title: 'Mr.',
		name: 'KFC-Active',
		abbreviation: 'JD',
		address: '123 Main St, Anytown, USA',
		biz_group: ['Retail', 'Food'],
		tax_id: 123456789,
		x_id: 987654321,
		is_active: true,
		is_delete: false,
		create_date: new Date(),
		update_date: new Date(),
	},
	{
		id: 2,
		title: 'Mr.',
		name: 'KFC-Inactive',
		abbreviation: 'JD',
		address: '123 Main St, Anytown, USA',
		biz_group: ['Retail', 'Food'],
		tax_id: 123456789,
		x_id: 987654321,
		is_active: false,
		is_delete: false,
		create_date: new Date(),
		update_date: new Date(),
	},
	{
		id: 3,
		title: 'Mr.',
		name: 'KFC-Active-Delete',
		abbreviation: 'JD',
		address: '123 Main St, Anytown, USA',
		biz_group: ['Retail', 'Food'],
		tax_id: 123456789,
		x_id: 987654321,
		is_active: true,
		is_delete: true,
		create_date: new Date(),
		update_date: new Date(),
	},
	{
		id: 4,
		title: 'Mr.',
		name: 'KFC-Inactive-Delete',
		abbreviation: 'JD',
		address: '123 Main St, Anytown, USA',
		biz_group: ['Retail', 'Food'],
		tax_id: 123456789,
		x_id: 987654321,
		is_active: false,
		is_delete: true,
		create_date: new Date(),
		update_date: new Date(),
	},
];
