export const registered_members = [
	{
		id: 1, // Age < 18
		external_members_id: 1,
		firstName: 'Prinnada',
		lastName: 'Comewinit',
		nationality: 'Thai',
		email: 'prinnada.c@gmail.com',
		phoneNumber: '0812345678',
		age: 16,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
	},
	{
		id: 2, // Age = 18
		external_members_id: 2,
		firstName: 'Pipat',
		lastName: 'Kaewsakulchai',
		nationality: 'Thai',
		email: 'pipat.k@gmail.com',
		phoneNumber: '0812345679',
		age: 18,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
	},
	{
		id: 3, // Age > 18
		external_members_id: 3,
		firstName: 'NeungZ',
		lastName: 'Kawaii',
		nationality: 'Thai',
		email: 'neungz.k@gmail.com',
		phoneNumber: '0812345679',
		age: 30,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
	},
	{
		id: 4, // Not active, not delete
		external_members_id: 4,
		firstName: 'Suriya',
		lastName: 'Metharom',
		nationality: 'Thai',
		email: 'suriya@gmail.com',
		phoneNumber: '0812345679',
		age: 18,
		is_active: false,
		is_delete: false,
		origin: 'Palace Blade',
	},
	{
		id: 5, // Not active, deleted
		external_members_id: 5,
		firstName: 'Arthit',
		lastName: 'Wattana',
		nationality: 'Thai',
		email: 'art.w@gmail.com',
		phoneNumber: '0812345679',
		age: 20,
		is_active: false,
		is_delete: true,
		origin: 'Palace Blade',
	},
	{
		id: 6, // Active, not delete
		external_members_id: 6,
		firstName: 'Somchai',
		lastName: 'Metharom',
		nationality: 'Thai',
		email: 'somchai.m@gmail.com',
		phoneNumber: '0812345679',
		age: 22,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade',
	},
	{
		id: 7, // Active, deleted
		external_members_id: 7,
		firstName: 'Kulap',
		lastName: 'Bunnag',
		nationality: 'Thai',
		email: 'kulap.b@gmail.com',
		phoneNumber: '0812345679',
		age: 24,
		is_active: true,
		is_delete: true,
		origin: 'Palace Blade',
	},
	{
		id: 8, // Age < 20
		external_members_id: 8,
		firstName: 'Ming',
		lastName: 'Wei',
		nationality: 'Chinese',
		email: 'mingming.w@gmail.com',
		phoneNumber: null,
		age: 16,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
	},
	{
		id: 9, // Age = 20
		external_members_id: 9,
		firstName: 'Yang',
		lastName: 'Yu',
		nationality: 'Chinese',
		email: 'yuyuyang.y@gmail.com',
		phoneNumber: null,
		age: 20,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
	},
	{
		id: 10, // Age > 20
		external_members_id: 10,
		firstName: 'Xun',
		lastName: 'Xu',
		nationality: 'Chinese',
		email: 'xunxu@gmail.com',
		phoneNumber: null,
		age: 30,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
	},
	{
		id: 11, // Not active, not delete
		external_members_id: 11,
		firstName: 'Hua',
		lastName: 'Xu',
		nationality: 'Chinese',
		email: 'huaxu@gmail.com',
		phoneNumber: null,
		age: 18,
		is_active: false,
		is_delete: false,
		origin: 'Palace Blade International',
	},
	{
		id: 12, // Not active, deleted
		external_members_id: 12,
		firstName: 'Heng',
		lastName: 'Lu',
		nationality: 'Chinese',
		email: 'luheng@gmail.com',
		phoneNumber: null,
		age: 20,
		is_active: false,
		is_delete: true,
		origin: 'Palace Blade International',
	},
	{
		id: 13, // Active, not delete
		external_members_id: 13,
		firstName: 'Tao',
		lastName: 'Xiao',
		nationality: 'Chinese',
		email: 'xiaotao@gmail.com',
		phoneNumber: null,
		age: 22,
		is_active: true,
		is_delete: false,
		origin: 'Palace Blade International',
	},
	{
		id: 14, // Active, deleted
		external_members_id: 14,
		firstName: 'Long',
		lastName: 'Chu',
		nationality: 'Chinese',
		email: 'longlong.c@gmail.com',
		phoneNumber: null,
		age: 24,
		is_active: true,
		is_delete: true,
		origin: 'Palace Blade International',
	},
];
