export const users = [
	{
		external_id: 'a001',
		first_name: 'pipat',
		last_name: 'kae',
		email: 'pipat.k@email.com',
		is_active: true,
		created_by: 'mock@mock.com',
		updated_by: 'mock@mock.com',
		role_id: 1,
	},
	{
		external_id: 'b001',
		email: 'prinada.c@email.com',
		first_name: 'prinada',
		last_name: 'co',
		is_active: true,
		phone_number: '0832223333',
		created_by: 'mock@mock.com',
		updated_by: 'mock@mock.com',
		role_id: 2,
	},
	{
		external_id: 'c001',
		email: 'inactive.user@email.com',
		first_name: 'inactive',
		last_name: 'user',
		is_active: false,
		phone_number: '0832223333',
		created_by: 'mock@mock.com',
		updated_by: 'mock@mock.com',
		role_id: 2,
	},
	{
		external_id: 'D001',
		email: 'inactive.deleted.user@email.com',
		first_name: 'inactived',
		last_name: 'deleted',
		is_active: false,
		is_deleted: true,
		phone_number: '0832223333',
		created_by: 'mock@mock.com',
		updated_by: 'mock@mock.com',
		role_id: 2,
	},
	{
		external_id: 'D002',
		email: 'active.deleted.user@email.com',
		first_name: 'active',
		last_name: 'deleted',
		is_active: true,
		is_deleted: true,
		phone_number: '0832223333',
		created_by: 'mock@mock.com',
		updated_by: 'mock@mock.com',
		role_id: 2,
	},
];
